name: Functional tests
on: [push]
jobs:
  simpletest:
    name: Simpletest batches
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        fraction: ['1/15']

    steps:
      - name: Setup MySQL and create database
        run: |
          # Disable apparmor for mysql.
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
          # Move datadir and tmpdir to shared memory.
          sudo mkdir /dev/shm/mysql_tmp
          sudo chown mysql:mysql /dev/shm/mysql_tmp
          sudo sed -i -e 's?datadir\s*=.*?datadir = /dev/shm/mysql?' \
            -e 's?tmpdir\s*=.*?tmpdir = /dev/shm/mysql_tmp?' /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo mv /var/lib/mysql /dev/shm
          sudo systemctl start mysql.service
          # Use .my.cnf to avoid user / password on commandline.
          echo -e '[client]\nuser = root\npassword = root' > ~/.my.cnf
          mysql -V
          mysql -e 'CREATE DATABASE backdrop;'

      - name: System status
        if: ${{ always() }}
        run: |
          sudo systemctl status mysql.service
          sudo tail /var/log/syslog
          echo Get load
          uptime
          echo Get mem usage
          free -m
          echo Get disk usage
          df -h
          echo Get running procs by user
          pgrep -au runner
