name: Functional tests
on: [push]
jobs:
  simpletest:
    name: Simpletest batches
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        fraction: ['9/15']

    steps:
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3800
          container port: 3307
          mariadb version: '10.3'
          mysql database: 'backdrop'
          mysql root password: 'root'

      - name: Check MariaDB
        run: |
          ps aux | grep my
          netstat -tapn
          # Use .my.cnf to avoid user / password on commandline.
          echo -e '[client]\nuser = root\npassword = root' > ~/.my.cnf
          mysql -p 3800 -V

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: none

      - name: Setup webserver
        run: |
          # Set up apache with php-fpm.
          sudo cp .github/misc/default.conf /etc/apache2/sites-available/000-default.conf
          sudo sed -i -e "s/_PHP_VERSION_/${{ matrix.php-versions }}/" /etc/apache2/sites-available/000-default.conf
          # Setup php-fpm, this script is by intention not executable by default.
          chmod 700 .github/misc/setup-php-fpm.sh
          ./.github/misc/setup-php-fpm.sh ${{ matrix.php-versions }}
          # This should be a redirect to the installer:
          echo 'Verify webserver setup'
          curl -sI 'http://localhost/'

      - name: Install Backdrop
        run: core/scripts/install.sh --db-url=mysql://root:root@127.0.0.1:3800/backdrop

      - name: Run tests
        run: |
          echo Running fraction ${{ matrix.fraction }} with PHP ${{ matrix.php-versions }}
          core/scripts/run-tests.sh --force --cache --verbose --color --directory=core --split=${{ matrix.fraction }} --concurrency 7

      - name: System status
        if: ${{ always() }}
        run: |
          echo Get load
          uptime
          echo Get mem usage
          free -m
          echo Get disk usage
          df -h
          echo Get running procs by user
          pgrep -au runner
